# Generated by Django 5.1.6 on 2025-03-05 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_cartitems"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartItems",
            new_name="CartItem",
        ),
    ]
