# Generated by Django 5.1.6 on 2025-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="preparation_time",
            field=models.IntegerField(default=10),
        ),
    ]
