# Generated by Django 5.1.6 on 2025-03-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_menuitem_preparation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
