# Generated by Django 5.1.6 on 2025-03-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_order_estimated_delivery_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="estimated_delivery_time",
            new_name="estimated_ready_time",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="timesatmp",
            new_name="timestamp",
        ),
    ]
